# Generated by Django 3.1.7 on 2021-05-31 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boec_core', '0002_auto_20210530_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Desc', max_length=255, null=True)),
                ('parent', models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.CASCADE, to='boec_core.category')),
            ],
        ),
    ]
