# Generated by Django 3.1.7 on 2021-06-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boec_core', '0012_auto_20210616_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
