# Generated by Django 3.1.7 on 2021-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boec_core', '0013_remove_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userlink',
            field=models.CharField(db_column='link', default='', max_length=100),
        ),
    ]
