# Generated by Django 3.1.7 on 2021-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boec_core', '0015_auto_20210617_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='offset',
            field=models.FloatField(blank=True, db_column='offset', max_length=255, null=True),
        ),
    ]
